version: 1.0.{build}
before_build:
  - nuget restore
configuration: Debug
platform: Any CPU
build:
  project: Route4MeSDK.sln 
  verbosity: minimal
assembly_info:
  patch: true
after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\Route4MeSDKUnitTest\bin\Debug\Route4MeSDKUnitTest.dll" 
    -output:".\Route4MeSDKUnitTest_coverage.xml"

    